### ISSUE TITLE
Redirect to home page from login

### ISSUE THREAD

**Issue by pisacode** [JackAdams/meteor-accounts-ldap-ionic#1]
Hi,

I am new to meteor,

How can i redirect succesfully logged in user to home page '/'  as in the accounts package's onSubmitHook?

I am also using your ldap package. Great package btw thanks a lot

**Comment by JackAdams** [comment]
Hi,
Glad you're finding the ldap package useful.  Is the `onSubmit` hook something that's fired on the client?  It's sounds like it's more of a `onSuccessfulLogin` type of hook that you're after.  This can probably be manufactured by watching `Meteor.user()` in an `autorun` function. Off the top of my head:
```
Tracker.autorun(function (c) {
  if (Meteor.user()) {
    Router.go('/');
    c.stop();
  }
});
```

**Comment by pisacode** [comment]
Hi thanks for the fast response. I have tried that and found out that each time page refreshes that method is called and therefore user is pushed to the main page.

I have approached to this issue as the following to prevent this issue, with the help of react router's browser history.

`Accounts.onLogin(function(){
    if(Meteor.userId() && browserHistory.getCurrentLocation().pathname=="/sign-in"){
      browserHistory.push('/')
    }
  })`

**Comment by JackAdams** [comment]
Ah yes. That's true. A page refresh would cause problems.
If you like, I can build in a `onSuccessfulLogin` hook. It would be pretty easy to do.

**Comment by JackAdams** [comment]
Just published `babrahams:accounts-ldap@0.7.5` and `babrahams:accounts-ldap-ionic@0.4.5`. There is now a new hook available: `LDAP.onSuccessfulLogin = function (user) {}` (overwrite with whatever functionality you need).

**Comment by pisacode** [comment]
thanks a lot @JackAdams

**Comment by pisacode** [comment]
Hi again,

I am trying to add multiple AD to the application and require users to choose their AD from selection box to implement their AD settings. However I couldn't succeed to change LDAP settings dynamically when user choose their AD from selection box. Do you have any idea how that could be done with your LDAP package.

Many Thanks

**Comment by JackAdams** [comment]
Take a look at the example code at the bottom of the README in the [accounts-ldap package](https://github.com/JackAdams/meteor-accounts-ldap). That was largely cut-and-pasted from a working multi-tenant app where tenants get to specify their own LDAP server on a settings page.

The key is to send a piece of info from client to server when logging in (in your case it would be the value of the AD selection box). You do this by overwriting the `LDAP.data` function on the client.  Then you can pick up this piece of data on the server and make the correct settings by overwriting the `LDAP.generateSettings` function.

**Comment by pisacode** [comment]
Thanks a lot, you have been a great help. And happy new year :)
